export const DEFAULT_PROHIBITED_WORDS: Array<{ word: string; category: string }> = [
  { word: 'delve', category: 'ai_ism' },
  { word: 'tapestry', category: 'ai_ism' },
  { word: 'resonate', category: 'ai_ism' },
  { word: 'landscape', category: 'ai_ism' },
  { word: 'testament', category: 'ai_ism' },
  { word: 'multifaceted', category: 'ai_ism' },
  { word: 'nuanced', category: 'ai_ism' },
  { word: 'intricate', category: 'ai_ism' },
  { word: 'pivotal', category: 'ai_ism' },
  { word: 'poignant', category: 'ai_ism' },
  { word: 'commendable', category: 'ai_ism' },
  { word: 'meticulous', category: 'ai_ism' },
  { word: 'groundbreaking', category: 'ai_ism' },
  { word: 'paradigm', category: 'ai_ism' },
  { word: 'synergy', category: 'ai_ism' },
  { word: 'holistic', category: 'ai_ism' },
  { word: 'robust', category: 'ai_ism' },
  { word: 'leverage', category: 'ai_ism' },
  { word: 'palpable', category: 'ai_ism' },
  { word: 'visceral', category: 'ai_ism' },
  { word: 'myriad', category: 'ai_ism' },
  { word: 'plethora', category: 'ai_ism' },
  { word: 'moreover', category: 'ai_ism' },
  { word: 'furthermore', category: 'ai_ism' },
  { word: 'consequently', category: 'ai_ism' },
  { word: 'nevertheless', category: 'ai_ism' },
  { word: 'a sense of', category: 'ai_ism' },
  { word: 'couldn\'t help but', category: 'ai_ism' },
  { word: 'sent shivers down', category: 'cliche' },
  { word: 'heart skipped a beat', category: 'cliche' },
  { word: 'pit of her stomach', category: 'cliche' },
  { word: 'pit of his stomach', category: 'cliche' },
  { word: 'blood ran cold', category: 'cliche' },
  { word: 'like a ton of bricks', category: 'cliche' },
  { word: 'let out a breath', category: 'overused' },
  { word: 'didn\'t realize', category: 'overused' },
  { word: 'exhaled a breath', category: 'overused' },
  { word: 'a shiver ran', category: 'overused' },
  { word: 'steeled himself', category: 'overused' },
  { word: 'steeled herself', category: 'overused' },
  { word: 'etched on', category: 'overused' },
  { word: 'knuckles white', category: 'overused' },
  { word: 'dark chuckle', category: 'overused' },
  { word: 'ragged breath', category: 'overused' },
];
